### PR TITLE
Refactored Example, CSS and added a README

### PR DESCRIPTION
**Pull request by kuzeko**

### CODE REVIEW

**Comment by Ragnis** [comment]
Could you please change your changes, to comply with the coding guidelines?
https://github.com/Ragnis/StickyHeaders/wiki/Coding-guidelines

And I'm not sure that the to-do list belongs to the README file. You should instead open new issues for the to-do items.

**Comment by kuzeko** [comment]
So issues for TODOs ? Ok

If you are referring to the TABs, well i think that TABs don't help very much, better is to use proper indented spaces cfr.http://www.jwz.org/doc/tabs-vs-spaces.html

**Comment by Ragnis** [comment]
I still think, that it would be better to go with tabs.

**Comment by kuzeko** [comment]
Why?

**Comment by Ragnis** [comment]
Sorry, I pasted a wrong thing there earlier.

http://www.derkarl.org/why_to_tabs.html
"It doesn't matter how deep your tabs are, the reader of the text file can just set their depth to whatever they want, and not have to reformat the file. "

**Comment by kuzeko** [comment]
I'll accept the tabs in the javascript as for the http://docs.jquery.com/JQuery_Core_Style_Guidelines#Spacing.

I think that in CSS and HTML we can stand with spaces as they are used in all the snippets and code I have and have seen.

**Comment by Ragnis** [comment]
Ok, CSS and HTML with 4 spaces.

And I noticed, that you have whitespace before your css selectors, that shouldn't be there.

**Comment by kuzeko** [comment]
It's ok now?

**Comment by Ragnis** [comment]
The indentation should be 4 spaces and I noticed, that you have whitespace before your css selectors, that shouldn't be there.

**Comment by kuzeko** [comment]
sorry, forgot to save ;)

**Pull request merged**
